apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartcms-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartcms-frontend
  template:
    metadata:
      labels:
        app: smartcms-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/danbugs/smartcms-frontend:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: smartcms-frontend
  namespace: default
spec:
  selector:
    app: smartcms-frontend
  ports:
    - port: 80
      targetPort: 80
