package component:smartcms;

interface kvstore {
    get: func(key: string) -> option<string>;
    set: func(key: string, value: string);
}

world app {
    import kvstore;
    import storygen: func() -> string;
    export run: func() -> string;
}