package smartcms:store-and-ai-story-generator;

world backend {
    import wasi:keyvalue/atomics@0.2.0-draft;
    import wasi:keyvalue/store@0.2.0-draft;
    import thomastaylor312:ollama/generate;
    export wasi:http/incoming-handler@0.2.2;
}
